global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "besu"
    metrics_path: /metrics
    static_configs:
      - targets:
          - "proxy1:9545"
          - "proxy2:9545"
          - "proxy3:9545"
          - "proxy4:9545"

  - job_name: "message_metrics_exporter"
    metrics_path: /metrics
    static_configs:
      - targets:
          - "host.docker.internal:3001"
